// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TiendaServicios.API.CarritoCompra.Persistence;

#nullable disable

namespace TiendaServices.API.CarritoCompra.Migrations
{
    [DbContext(typeof(ContextCarrito))]
    [Migration("20240310181706_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TiendaServices.API.CarritoCompra.Models.CarritoSession", b =>
                {
                    b.Property<int?>("CarritoSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.HasKey("CarritoSessionId");

                    b.ToTable("CarritoSession");
                });

            modelBuilder.Entity("TiendaServices.API.CarritoCompra.Models.CarritoSessionDetalle", b =>
                {
                    b.Property<int>("CarritoSessionDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CarritoSessionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaOperacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ProductoSelecioado")
                        .HasColumnType("longtext");

                    b.HasKey("CarritoSessionDetalleId");

                    b.HasIndex("CarritoSessionId");

                    b.ToTable("CarritoSessionDetalle");
                });

            modelBuilder.Entity("TiendaServices.API.CarritoCompra.Models.CarritoSessionDetalle", b =>
                {
                    b.HasOne("TiendaServices.API.CarritoCompra.Models.CarritoSession", "CarritoSession")
                        .WithMany("ListaDetalhe")
                        .HasForeignKey("CarritoSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarritoSession");
                });

            modelBuilder.Entity("TiendaServices.API.CarritoCompra.Models.CarritoSession", b =>
                {
                    b.Navigation("ListaDetalhe");
                });
#pragma warning restore 612, 618
        }
    }
}
